# Generated by Django 5.2.4 on 2025-08-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_userprofile_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rsvp_limit',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
