# Generated by Django 5.2.4 on 2025-08-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_event_created_by_event_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
